# Unsupervised feature learning

Assume that we do not know the actual labels of a bunch of opinions or any other dataset. We can perform unsupervised feature learning to extract the labels of a unlabeled dataset. This is very useful, since when we scrap free text from the web we can label it in order to perform unsupervised learning techniques to predict or classify new instances. I will use the same opinions of my [thesis](http://132.248.9.195/ptd2016/mayo/307602673/Index.html), the task was about perform sentiment analysis from a corpus of washing machine reviews in spanish (i.e. sentiment classification from 1-5 stars).


## First read the data:

In [41]:
import pandas as pd


df = pd.read_csv('/Users/user/jupyter_notebooks/unsupervised_feature_learning/data/new_corpus.csv', sep = '|', names=['id','content']).dropna()


X = df['content']

#y = df['label'].values
df.head()

id  \
0  AEG_Electrolux_60840_Lavamat__Opinion_1506705....   
1  AEG_Electrolux_62610_Lavamat__Opinion_2000923....   
2  AEG_Electrolux_L14800VI__Opinion_2005396.html.txt   
3   AEG_Electrolux_L6227FL__Opinion_2140710.html.txt   
4  AEG_Electrolux_L62280FL__Opinion_2151025.html.txt   

                                             content  
0   'Silencio y facilidad. Con estas dos palabras...  
1   'Hola compis!No sabía como se ponía una lavad...  
2   'Esta lavadora es de lo más práctica para aqu...  
3   'Buenas tardes amigos y compañeros de ciao......  
4   'Empecemos por una ventaja muy importante: la...

## Vectorize our data

In [52]:

from sklearn.feature_extraction.text import CountVectorizer
count_vect = CountVectorizer()
X = count_vect.fit_transform(X)
X.toarray()

array([[0, 1, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       ..., 
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0]], dtype=int64)

## With K-means:

In [16]:
from sklearn import cluster
k_means = cluster.KMeans(n_clusters=5)
k_means.fit(X)

KMeans(copy_x=True, init='k-means++', max_iter=300, n_clusters=5, n_init=10,
    n_jobs=1, precompute_distances='auto', random_state=None, tol=0.0001,
    verbose=0)

## We learned the labels:

In [19]:
k_means.labels_[::10]

array([3, 1, 3, 3, 3, 3, 3, 3, 2, 0, 2, 3, 1, 3, 3, 3, 3, 3, 1, 2, 1, 1, 3,
       3, 3, 3, 3, 3, 4, 3, 3, 1, 4, 3, 4, 3, 2, 3, 3, 2, 2, 3, 3, 3, 3, 3,
       3, 1, 3, 3, 1, 3, 3, 1, 3, 3, 3, 3, 3, 3, 0, 2, 3, 3, 3, 3, 3, 3, 2,
       3, 1, 4, 3, 1, 4, 3, 3, 3, 3, 3, 3, 1, 3, 1, 3, 4, 3, 3, 3, 3, 3, 3,
       1, 1, 3, 3, 3, 3, 3, 1, 3, 0, 3, 2, 3, 3, 1, 3, 3, 3, 3, 3, 1, 1, 3,
       3, 4, 3, 1, 1, 3, 3, 3, 3, 3, 1, 3, 3, 3, 1, 3, 3, 4, 1, 3, 3, 4, 3,
       3, 3, 3, 4, 1, 3, 3, 3, 3, 3, 3, 3, 2, 3, 3, 3, 3, 3, 3, 3, 1, 3, 3,
       3, 1, 4, 3, 3, 3, 3, 3, 4, 3, 1, 1, 4, 3, 3, 3, 4, 3, 3, 3, 1, 2, 3,
       1, 3, 3, 3, 3, 3, 3, 3, 3, 1, 1, 3, 1, 4, 2, 1, 3, 1, 1, 1, 4, 3, 1,
       3, 3, 4, 3, 3, 3, 3, 4, 3, 3, 1, 3, 1, 3, 3, 3, 1, 1, 3, 3, 3, 0, 3,
       3, 3, 3, 3, 2, 3, 3, 2, 1, 3, 3, 3, 1, 2, 3, 3, 3, 2, 3, 3, 1, 1, 3,
       3, 3, 3, 0, 0, 3, 3, 3, 3], dtype=int32)

In [24]:
y = k_means.labels_
type(y)

numpy.ndarray

## Now let's rearrange the dataframe 

In [45]:
df['labels'] = y

In [46]:
df.head()

id  \
0  AEG_Electrolux_60840_Lavamat__Opinion_1506705....   
1  AEG_Electrolux_62610_Lavamat__Opinion_2000923....   
2  AEG_Electrolux_L14800VI__Opinion_2005396.html.txt   
3   AEG_Electrolux_L6227FL__Opinion_2140710.html.txt   
4  AEG_Electrolux_L62280FL__Opinion_2151025.html.txt   

                                             content  labels  
0   'Silencio y facilidad. Con estas dos palabras...       3  
1   'Hola compis!No sabía como se ponía una lavad...       3  
2   'Esta lavadora es de lo más práctica para aqu...       3  
3   'Buenas tardes amigos y compañeros de ciao......       3  
4   'Empecemos por una ventaja muy importante: la...       3

In [49]:
df['labels'].value_counts()

3    1753
1     543
2     181
4     106
0      35
Name: labels, dtype: int64

## With DBSCAN

Now let's assume that we do not know with how many stars perform classification, let's use DBSCAN.

In [55]:
from sklearn.cluster import DBSCAN
db_scan = DBSCAN()
db_scan.fit(X)


DBSCAN(algorithm='auto', eps=0.5, leaf_size=30, metric='euclidean',
    min_samples=5, p=None, random_state=None)

In [56]:
db_scan.labels_[::10]

array([-1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1,
       -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1,
       -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1,
       -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1,
       -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1,
       -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1,
       -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1,
       -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1,
       -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1,
       -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1,
       -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1,
       -1, -1, -1, -1,  0, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1,
       -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1,
       -1, -1, -1, -1, -1

In [58]:
y = db_scan.labels_
type(y)

numpy.ndarray

In [59]:
df['labels'] = y

In [61]:
df.head()

id  \
0  AEG_Electrolux_60840_Lavamat__Opinion_1506705....   
1  AEG_Electrolux_62610_Lavamat__Opinion_2000923....   
2  AEG_Electrolux_L14800VI__Opinion_2005396.html.txt   
3   AEG_Electrolux_L6227FL__Opinion_2140710.html.txt   
4  AEG_Electrolux_L62280FL__Opinion_2151025.html.txt   

                                             content  labels  
0   'Silencio y facilidad. Con estas dos palabras...      -1  
1   'Hola compis!No sabía como se ponía una lavad...      -1  
2   'Esta lavadora es de lo más práctica para aqu...      -1  
3   'Buenas tardes amigos y compañeros de ciao......      -1  
4   'Empecemos por una ventaja muy importante: la...      -1

In [62]:
df['labels'].value_counts()

-1    2596
 0      22
Name: labels, dtype: int64